####################
# EXECUTION CONFIG #
####################

[Global]

# Duration (s)
duration: 100
# Ticker period (ms)
period: 1
# Multithreading: enabled (true), disabled (false). Single thread execution is only used for debugging purposes
multithreading: true
# Number of threads
threads: 16
# Output verbosity: verbose (true), non-verbose (false)
verbose: true



######
# UE #
######

[UE]

###################
# BASIC UE CONFIG #
###################
# UE ID
ue_id: idSimulated
# UE type: real UE (0), simulated UE (1)
ue_type: 1
# UL Netfilter Queue index (only in case of real UE)
# ul_queue_n: 0
# DL Netfilter Queue index (only in case of real UE)
# dl_queue_n: 1
# Number of UEs
n_ues: 20

############################
# UE PHYSICAL LAYER CONFIG #
############################
# Number of physical antennas in the UE
n_antennas: 4
#
alpha_ul: 0.8
#
nominal_pusch_p0: -50
#
set_ul_pow: true
# Transmission power (dBm)
tx_power_ul: 23
# CQI stimation period (ms)
cqi_period: 1
# RI stimation period (ms)
ri_period: 1
# Scaling factor. It is used for carrier aggregation throughput calculation. It is signaled by the eNB/gNB in a real deployment. It can take the values: 1, 0.8, 0.75, 0.4
scaling_factor: 1
#
random_v: false

###################
# LOG DATA CONFIG #
###################
#
log_freq: 1000
#
log_ue: true
#
log_quality: true
#
log_traffic: true
#
log_mobility: true

########################
# TRAFFIC MODEL CONFIG #
########################
# Traffic generator type: simulated (0), injected (1)
traffic_type: 0
# Path to file from which read the packets for UL transmission direction (only if injected traffic is used)
# ul_traffic_file:
# Path to file from which read the packets for DL transmission direction (only if injected traffic is used)
# dl_traffic_file:
# UL throughput target (Mbps, only if simulated traffic is used)
ul_target: 0.0
# DL throughput target (Mbps, only if simulated traffic is used)
dl_target: 100.0
# Throughput variance (%, only if simulated traffic is used)
var_perc: 0.00
# Packet size (bits)
pkt_size: 1000

#########################
# MOBILITY MODEL CONFIG #
#########################
# Mobility type: static model (0), random walk model (1), random waypoint model (2), random Manhattan model (3), linear drift model (4), clockwise model (5)
mobility_type: 2
# Initial position x coordinate (m)
pos_x: 1
# Initial position y coordinate (m)
pos_y: 1
# Create UE in a random position: true, false
random_init: true
# UE speed (km/h)
speed: 30.0
# UE speed variance (km/h)
speed_var: 0.0
# Maximum distance to eNB (m)
max_distance: 500
# Targed time used in some mobility models (s)
time_target: 5
# Targed time variance (s)
time_target_var: 2

#####################
# SCHEDULING CONFIG #
#####################
# UE priority (higher numbers means a higher priority)
priority: 1
# Acceptable packet loss rate (delta) parameter
delta_metric: 1.0
# Delay threshold (tau sub i) parameter
delay_t_metric: 0.1
# Beta parameter
beta_metric: 0.01

##############################
# SCENARIO-RELATED UE CONFIG #
##############################
# UE height (m)
ue_height: 1.5
# Output-to-input model: outdoor (10), in building (11), in car (12), random (13)
o2i: 10



#################
# SCENARIO CONFIG
#################

[Scenario]

# Scenario type: urban microcel (0), urban macrocell (1), rural macrocell (2), indoor hotspot (3), indoor factory (4)
scenario_type: 2
# Street width (m)
# street_width: 10
# eNB antenna height (m)
# antenna_height: 1
# eNB building height (m)
# enb_height: 5



############
# eNB CONFIG
############

[eNBConfig]

# Modulation: 6 bits 64QAM (0), 8 bits 256QAM (1), 2 bits QPSK, 4 bits 16QAM
modulation_m: 0
# Target BER (%)
target_ber: 0.1
# SNR-CQI calculation mode: wideband (0), sub-band (1)
cqi_mode: 0
# Transmission power (dBm)
tx_power: 43.0
# eNB antenna gain (dB)
eNB_gain: 0.0
# UT antenna gain (dB)
UT_gain: 0.0
# this is for RSRP calculation
power_boost: 2
# Carrier frequency (Hz)
frequency: 2000000000.0
# Bnadwidth (Hz)
bandwidth: 20000000



#######################
# PDCP/RLC Layer CONFIG
#######################

[PDCP_RLC]

# Backhauling delay for release buffer (s)
backhaul_d: 0.003
# Backhauling delay variance (s)
backhaul_d_var: 0.0
# Enable RLC reordering: true, false
order_pkts: true



##################
# MAC Layer CONFIG
##################

[MACLayer]

###################
# LOG DATA CONFIG #
###################
#
log_freq: 1000
#
log_mac: true

##########################
# BASIC MAC LAYER CONFIG #
##########################
# Number of available MIMO layers
mimo_layers: 1

###############
# HARQ CONFIG #
###############
# Maximum number of retransmissions for UL HARQ packets
max_rtx_ul: 4
# Maximum number of retransmissions for DL HARQ packets
max_rtx_dl: 4

#####################
# SCHEDULING CONFIG #
#####################
# Metric type: FIFO (0), BET (1), EDF (2), LWDF (3), MT (4), RR (5), PF (6)
metric_type: 0
# OFDM symbols per RB
ofdm_symbols: 14
# Numerology type (see Numerology.png table): 0, 1, 2, 3, 4, 5
numerology: 0
# Use MCS tables or SNR Gap Eq.
mcs_tables: false
# Scheduling mode: time RBs are separated in individual slots in distributed mode (0), time RBs are grouped in a single RBG in grouped mode (1)
scheduling_mode: 0
# Scheduling type: frequency RBs are grouped in RBGs (0), frequency RBs are not grouped in RBGs (1)
scheduling_type: 1
# Scheduling configuration (only if frequency RBs grouping in RBGs is selected, see TypeAllocation.png table): 1, 2
scheduling_config: 1

####################
# DUPLEXING CONFIG #
####################
# Duplexing type: TDD (0), FDD (1)
duplexing_type: 1
# Number of DL slots within a TDD configuration pattern (only if TDD is selected)
n_dl_slots: 7
# Number of UL slots within a TDD configuration pattern (only if TDD is selected)
n_ul_slots: 3
# Number of DL/UL Resource Elements available within the transtion (DL <-> UL) slot (only if TDD is selected)
transition_c: 54
# BW percentage occupied by the DL (only if FDD is selected)
ratio_DL_UL: 0.5



##################
# PHY Layer CONFIG
##################

[PHYLayer]

#############################
# NOISE INTERFERENCE CONFIG #
#############################
# Number of interfering UEs
interference_ues: 19
#
interference_eNBs: 4
#
distance_interference: 3000
#
interfered_bandwidth_ratio: 0.1
#
enb_noise_figure: 2
#
ut_noise_figure: 9

####################
# AIR DELAY CONFIG #
####################
# Air propagation delay variance in UL (s)
air_delay_var_ul: 0.0
# Air propagation delay variance in DL (s)
air_delay_var_dl: 0.0

###############
# HARQ CONFIG #
###############
# ACK/NACK delay for UL HARQ packets (s)
rtx_period_ul: 0.004
# ACK/NACK delay variance for UL HARQ packets (s)
rtx_period_var_ul: 0
# ACK/NACK processing delay for UL HARQ packets (s)
rtx_proc_delay_ul: 0.002
# ACK/NACK processing delay variance for UL HARQ packets (s)
rtx_proc_delay_var_ul: 0.0
# ACK/NACK delay for DL HARQ packets (s)
rtx_period_dl: 0.005
# ACK/NACK delay variance for DL HARQ packets (s)
rtx_period_var_dl: 0
# ACK/NACK processing delay for DL HARQ packets (s)
rtx_proc_delay_dl: 0.002
# ACK/NACK processing delay variance for DL HARQ packets (s)
rtx_proc_delay_var_dl: 0.0
